name: hive
description: Lightweight and buzzing-fast key-value database made for Flutter and Dart.
version: 4.0.0-dev.1
repository: https://github.com/isar/hive
homepage: https://github.com/isar/hive
issue_tracker: https://github.com/isar/hive/issues
funding:
  - https://github.com/sponsors/simc/
topics:
  - database
  - hive
  - nosql
  - encryption
  - storage

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  isar: ^4.0.0-dev.13
  meta: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.23.0
  very_good_analysis: ^5.0.0
