name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 1.1.0
homepage: https://github.com/hivedb/hive/tree/master/hive_flutter
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.1
  path_provider: ^2.0.10
  path: ^1.8.2

dev_dependencies:
  test: ^1.21.1
  lints: ^2.0.0
  mockito: ^5.2.0
  build_runner: ^2.1.11
