name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 0.5.0
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/hive

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  build: ^1.1.6
  source_gen: ^0.9.4+4
  hive: ">=0.4.0 <1.0.0"
  analyzer: ">=0.36.0 <0.40.0"


dev_dependencies:
  test: ^1.6.4
  build_test: any
  build_runner: any
  pedantic: '1.7.0'