name: hive
description: Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
version: 3.0.0-dev
homepage: https://github.com/hivedb/hive/tree/master/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  meta: ^1.9.1
  crypto: ^3.0.3
  js: ^0.6.8

dev_dependencies:
  test: ^1.24.2
  mocktail: ^0.3.0
  lints: ^2.1.0
  path: ^1.8.3
  pointycastle: ^3.7.3
  build_runner: ^2.4.1
