name: hive
description: Lightweight and blazing fast key-value database written in pure Dart. Stronly encrypted using AES-256.
version: 1.1.0-beta3
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/hivedb/hive

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  path: ">=1.6.0 <1.7.0"
  pointycastle: ^1.0.1
  meta: ^1.1.7

dev_dependencies:
  test: ^1.9.1
  mockito: ^4.1.1
  pedantic: '1.7.0'