name: hive
description: Lightweight and blazing fast key-value database written in pure Dart. Stronly encrypted using AES-256.
version: 0.5.0+1
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/hive

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  path: ">=1.6.0 <1.7.0"
  pointycastle: ^1.0.1
  meta: ^1.1.6

dev_dependencies:
  test: ^1.6.4
  mockito: ^4.1.0
  pedantic: '1.7.0'