name: Coverage

on:
  push:
    branches:
    - master

jobs:
  coverage-hive:
    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Collect coverage
      run: |
        pub get
        pub global activate test_coverage
        pub global run test_coverage --exclude "**/js/**"
      working-directory: hive
    - uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: hive/coverage/lcov.info
